---
- hosts: webservers
  become: true
  become_method: sudo
  gather_facts: true
  tasks:
    - name: apt update
      apt:
        update_cache: true

    - name: Installing pip3
      apt:
       name: python3-pip
       state: latest
       update_cache: true

    - name: Installing flask
      pip:
        executable: pip3
        name: flask
        state: latest

    - name: Copy Application2.py
      copy:
        src: /$PWD/application2.py
        dest: /home/ubuntu/application2.py
        owner: ubuntu
        mode: '0644'


# haproxy configuration
- hosts: all
  gather_facts: true
- hosts: HAproxy
  become: true

  tasks:

    - name: apt update
      apt:
        update_cache: yes

    - name: Installing HAPROXY
      apt:
        name: haproxy
        state: present

    - name: Configure haproxy
      template:
        src: /$PWD/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
 
    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted
